### ISSUE TITLE
对比表格后会报错

### ISSUE THREAD

**Issue by niko015** [obiscr/ExcelEditor#4]
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 8
	at java.base/java.util.Vector.get(Vector.java:750)
	at com.github.obiscr.exceleditor.ui.diff.a.a(SourceFile:99)
	at com.github.obiscr.exceleditor.ui.diff.a.a(SourceFile:71)
	at com.github.obiscr.exceleditor.ui.diff.e.<init>(SourceFile:53)
	at com.github.obiscr.exceleditor.ui.diff.c.<init>(SourceFile:26)
	at com.github.obiscr.exceleditor.ui.diff.impl.ExcelDiffManagerImpl.a(SourceFile:44)
	at com.github.obiscr.exceleditor.ui.diff.impl.ExcelDiffManagerImpl.a(SourceFile:98)
	at com.github.obiscr.exceleditor.ui.diff.a.a.a(SourceFile:62)
	at com.github.obiscr.exceleditor.ui.diff.a.e$a.actionPerformed(SourceFile:124)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

文件对比链接: https://pan.baidu.com/s/1Lk7aCVkLgOdjy7h8D6wQAg?pwd=2z9x 提取码: 2z9x 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v5的分享

**Comment by obiscr** [comment]
感谢反馈，我先尝试复现一下。

**Comment by obiscr** [comment]
这个问题已经修复。麻烦关注后续的更新，但是我发现您提供的两个excel文件，没有表头（第一行是空的）。要是正常对比的话，请确保文件表头是完整的，不然可能会出现意料之外的结果。

**Comment by niko015** [comment]
因为要兼顾游戏app前端配置表与后端配置表，所以表头在我们内部使用了统一的格式，有的是有内容的，有的是没有内容，但是固定行填写固定位置需要的字段，刚好这个表第一行不需要填写那些字段，所以才是您看到的这种，表头是空行的情况



***@***.***
 
发件人： 吳子玄
发送时间： 2022-11-16 20:17
收件人： obiscr/ExcelEditor
抄送： niko015; Author
主题： Re: [obiscr/ExcelEditor] 对比表格后会报错 (Issue #4)
这个问题已经修复。麻烦关注后续的更新，但是我发现您提供的两个excel文件，没有表头（第一行是空的）。要是正常对比的话，请确保文件表头是完整的，不然可能会出现意料之外的结果。
